[package]
name = "os-info"
version = "0.1.4"
edition = "2024"
description = "A command-line tool to print information about the current operating system."
license = "MIT"
repository = "https://github.com/os-info-contributors/os-info"
homepage = "https://github.com/os-info-contributors/os-info"
documentation = "https://docs.rs/os-info"
readme = "README.md"
keywords = ["os-info", "cli", "system-info"]
categories = ["command-line-utilities"]
include = ["src/**", "tests/**", "platform/**", "docs/**", "build.rs", "Cargo.toml", "README.md", "LICENSE", "NOTICE", "SECURITY.md", "CONTRIBUTING.md", "CHANGELOG.md", "deny.toml"]

[dependencies]
os_info = "3.15.0"
sysinfo = { version = "0.33.1", default-features = false, features = ["system"] }
